memoryoracle.models.Instance Class Reference
Classes
class Meta
Static Public Attributes
tuple id = models.CharField(primary_key=True, max_length=36)
tuple id_commit = models.ForeignKey(Commit, db_column='id_commit', blank=True, null=True)
Detailed Description
Definition at line 183 of file models.py.
Member Data Documentation
tuple memoryoracle.models.Instance.id = models.CharField(primary_key=True, max_length=36) [static]
Definition at line 184 of file models.py.
Referenced by memoryoracle.instance.Instance._basic_track(), memoryoracle.instance.StructureInstance._track(), memoryoracle.instance.Array._track(), and memoryoracle.instance.Pointer._track().
tuple memoryoracle.models.Instance.id_commit = models.ForeignKey(Commit, db_column='id_commit', blank=True, null=True) [static]
Definition at line 185 of file models.py.
The documentation for this class was generated from the following file:
memoryoracle/models.py