memoryoracle.models.Float Class Reference
Classes
class Meta
Static Public Attributes
tuple id = models.CharField(primary_key=True, max_length=36)
tuple id_program_instance = models.ForeignKey('ProgramInstance', db_column='id_program_instance')
tuple value = models.CharField(max_length=200)
tuple address = models.CharField(max_length=200)
Detailed Description
Definition at line 161 of file models.py.
Member Data Documentation
tuple memoryoracle.models.Float.address = models.CharField(max_length=200) [static]
Definition at line 165 of file models.py.
Referenced by memoryoracle.instance.Instance._clear_updated(), and memoryoracle.instance.Instance.index().
tuple memoryoracle.models.Float.id = models.CharField(primary_key=True, max_length=36) [static]
Definition at line 162 of file models.py.
Referenced by memoryoracle.instance.Instance._basic_track(), memoryoracle.instance.StructureInstance._track(), memoryoracle.instance.Array._track(), and memoryoracle.instance.Pointer._track().
tuple memoryoracle.models.Float.id_program_instance = models.ForeignKey('ProgramInstance', db_column='id_program_instance') [static]
Definition at line 163 of file models.py.
tuple memoryoracle.models.Float.value = models.CharField(max_length=200) [static]
Definition at line 164 of file models.py.
The documentation for this class was generated from the following file:
memoryoracle/models.py