memoryoracle.models.FunctionCall Class Reference
Classes
class Meta
Static Public Attributes
tuple id = models.CharField(primary_key=True, max_length=36)
tuple id_function = models.CharField(max_length=36)
tuple id_program_instance = models.CharField(max_length=36)
tuple id_field = models.CharField(db_column='id_', max_length=45, blank=True)
Detailed Description
Definition at line 172 of file models.py.
Member Data Documentation
tuple memoryoracle.models.FunctionCall.id = models.CharField(primary_key=True, max_length=36) [static]
Definition at line 173 of file models.py.
Referenced by memoryoracle.instance.Instance._basic_track(), memoryoracle.instance.StructureInstance._track(), memoryoracle.instance.Array._track(), and memoryoracle.instance.Pointer._track().
tuple memoryoracle.models.FunctionCall.id_field = models.CharField(db_column='id_', max_length=45, blank=True) [static]
Definition at line 176 of file models.py.
tuple memoryoracle.models.FunctionCall.id_function = models.CharField(max_length=36) [static]
Definition at line 174 of file models.py.
tuple memoryoracle.models.FunctionCall.id_program_instance = models.CharField(max_length=36) [static]
Definition at line 175 of file models.py.
The documentation for this class was generated from the following file:
memoryoracle/models.py