memoryoracle.execution.Executable Class Reference
Static Public Attributes
tuple name = mongoengine.StringField()
tuple path = mongoengine.StringField()
tuple hash_sha256 = mongoengine.StringField()
tuple hash_sha384 = mongoengine.StringField()
tuple hash_sha512 = mongoengine.StringField()
tuple version = mongoengine.StringField()
tuple executions = mongoengine.ListField(mongoengine.ReferenceField(Execution))
Detailed Description
*Concrete* class representing a executable file generated by running
build on a commit
Definition at line 34 of file execution.py.
Member Data Documentation
tuple memoryoracle.execution.Executable.executions = mongoengine.ListField(mongoengine.ReferenceField(Execution)) [static]
Definition at line 45 of file execution.py.
tuple memoryoracle.execution.Executable.hash_sha256 = mongoengine.StringField() [static]
Definition at line 41 of file execution.py.
tuple memoryoracle.execution.Executable.hash_sha384 = mongoengine.StringField() [static]
Definition at line 42 of file execution.py.
tuple memoryoracle.execution.Executable.hash_sha512 = mongoengine.StringField() [static]
Definition at line 43 of file execution.py.
tuple memoryoracle.execution.Executable.name = mongoengine.StringField() [static]
Definition at line 39 of file execution.py.
Referenced by memoryoracle.instance.Memory._basic_track(), memoryoracle.instance.Structure._track(), memoryoracle.instance.Pointer._track(), memoryoracle.descriptions.MemoryDescription.dict(), memoryoracle.watch.AddressableWatcher.stop(), and memoryoracle.instance.Primitive.val_string().
tuple memoryoracle.execution.Executable.path = mongoengine.StringField() [static]
Definition at line 40 of file execution.py.
tuple memoryoracle.execution.Executable.version = mongoengine.StringField() [static]
Definition at line 44 of file execution.py.
The documentation for this class was generated from the following file:
memoryoracle/execution.py