memoryoracle.frame.Frame Class Reference
Public Member Functions
def __init__ (self, gdbFrame)
def __str__ (self)
def __repr__ (self)
def index (self)
def is_valid (self)
def name (self)
def architecture (self)
def type (self)
def unwind_stop_reason (self)
def pc (self)
def block (self)
def function (self)
def older (self)
def newer (self)
def find_sal (self)
def read_register (self, register)
def read_var
def select (self)
Public Attributes
frame
description
Static Public Attributes
tuple knownFrames = dict()
Private Member Functions
def _get_frame
Detailed Description
*Concrete* class to track a frame in the debugee
Definition at line 9 of file frame.py.
Constructor & Destructor Documentation
def memoryoracle.frame.Frame.__init__ (self, gdbFrame)
Definition at line 20 of file frame.py.
    def __init__(self, gdbFrame):
        self.frame = gdbFrame
        self.description = str(self.frame)
        if self.frame.is_valid():
            self.knownFrames[self.description] = self
Member Function Documentation
def memoryoracle.frame.Frame.__repr__ (self)
Definition at line 30 of file frame.py.
References memoryoracle.frame.Frame.frame.
    def __repr__(self):
        return repr(self.frame)
def memoryoracle.frame.Frame.__str__ (self)
Definition at line 27 of file frame.py.
References memoryoracle.frame.Frame.frame.
    def __str__(self):
        return str(self.frame)
def memoryoracle.frame.Frame._get_frame (self, gdbFrame = None) [private]
Definition at line 17 of file frame.py.
    def _get_frame(self, gdbFrame=None):
        return gdbFrame if gdbFrame is not None else gdb.selected_frame()
def memoryoracle.frame.Frame.architecture (self)
Definition at line 43 of file frame.py.
    def architecture(self):
        return self.frame.architecture()
def memoryoracle.frame.Frame.block (self)
Definition at line 55 of file frame.py.
    def block(self):
        return self.frame.block()
def memoryoracle.frame.Frame.find_sal (self)
Definition at line 67 of file frame.py.
    def find_sal(self):
        return self.frame.find_sal()
def memoryoracle.frame.Frame.function (self)
Definition at line 58 of file frame.py.
    def function(self):
        return self.frame.function()
def memoryoracle.frame.Frame.index (self)
Definition at line 34 of file frame.py.
Referenced by memoryoracle.models.Typed.__init__(), memoryoracle.instance.Memory._basic_track(), and memoryoracle.models.Memory._clear_updated().
    def index(self):
        return str(self)
def memoryoracle.frame.Frame.is_valid (self)
Definition at line 37 of file frame.py.
    def is_valid(self):
        return self.frame.is_valid()
def memoryoracle.frame.Frame.name (self)
Definition at line 40 of file frame.py.
    def name(self):
        return self.frame.name()
def memoryoracle.frame.Frame.newer (self)
Definition at line 64 of file frame.py.
    def newer(self):
        return Frame(self.frame.newer())
def memoryoracle.frame.Frame.older (self)
Definition at line 61 of file frame.py.
    def older(self):
        return Frame(self.frame.older())
def memoryoracle.frame.Frame.pc (self)
Definition at line 52 of file frame.py.
    def pc(self):
        return self.frame.pc()
def memoryoracle.frame.Frame.read_register (self, register)
Definition at line 70 of file frame.py.
    def read_register(self, register):
        return self.frame.read_register()
def memoryoracle.frame.Frame.read_var (self, variable, block = None)
Definition at line 73 of file frame.py.
    def read_var(self, variable, block = None):
        if block is not None:
            return self.frame.read_var(variable, block)
        else:
            return self.frame.read_var(variable)
def memoryoracle.frame.Frame.select (self)
Definition at line 79 of file frame.py.
    def select(self):
        self.frame.select()
def memoryoracle.frame.Frame.type (self)
Definition at line 46 of file frame.py.
    def type(self):
        return self.frame.type()
def memoryoracle.frame.Frame.unwind_stop_reason (self)
Definition at line 49 of file frame.py.
    def unwind_stop_reason(self):
        return self.frame.unwind_stop_reason()
Member Data Documentation
memoryoracle.frame.Frame.description
Definition at line 22 of file frame.py.
Referenced by memoryoracle.instance.Int._track().
memoryoracle.frame.Frame.frame
Definition at line 21 of file frame.py.
Referenced by memoryoracle.frame.Frame.__repr__(), memoryoracle.frame.Frame.__str__(), memoryoracle.descriptions.MemoryDescription.dict(), and memoryoracle.instance.Primitive.val_string().
tuple memoryoracle.frame.Frame.knownFrames = dict() [static]
Definition at line 15 of file frame.py.
The documentation for this class was generated from the following file:
memoryoracle/frame.py