memoryoracle.instance Namespace Reference
Classes
class Array
class Call
class CharString
class ConstDecorator
class ExternDecorator
class Float
class Int
class MemberDecorator
class Memory
class MemoryWatcher
class Pointer
class Primitive
class RegisterDecorator
class StateSerializer
class StaticDecorator
class Structure
class Void
class VolatileDecorator
Functions
def addressable_factory (description)
def get_frame_symbols
def serialize_frame_globals
def serialize_upward
def serialize_block_locals
def serialize_frame_locals
def target_type_name (t)
def stopped (event)
Variables
tuple connection
db = connection.memoryoracle
tuple frameDescription = descriptions.MemoryDescription(`yourframe`)
tuple f = frame.Frame(gdb.selected_frame())
tuple e = execution.Execution()
tuple d = descriptions.MemoryDescription(`a`, address=`1`, execution=e)
tuple x = Float.factory(descript=d)
Function Documentation
def memoryoracle.instance.addressable_factory (description)
Definition at line 519 of file instance.py.
Referenced by memoryoracle.instance.Structure._track(), memoryoracle.instance.Pointer._track(), memoryoracle.instance.Int._track(), memoryoracle.instance.serialize_block_locals(), and memoryoracle.instance.serialize_frame_locals().
def addressable_factory(description):
    _stdLibChecker = re.compile("^std::.*")
    s = description.object
    if s is not None:
        standardLib = _stdLibChecker.match(descriptions.type_name(s.type))
        description._address = s.address
        handler = typed.type_lookup(s.type.strip_typedefs().code)
        if standardLib:
            return tracked.StandardDecorator(handler(description), toTrack = False)
        return handler(description)
    else:
        return Untracked()
def memoryoracle.instance.get_frame_symbols (frm = None)
Definition at line 533 of file instance.py.
Referenced by memoryoracle.instance.serialize_frame_locals().
def get_frame_symbols(frm=None):
    with frame.Selector(frm) as fs:
        f = fs.frame
        if f.is_valid():
            return { str(sym) for sym in f.block() }
        else:
            raise Exception("Frame no longer valid")
def memoryoracle.instance.serialize_block_locals (blk = None)
Definition at line 554 of file instance.py.
References memoryoracle.instance.addressable_factory().
Referenced by memoryoracle.instance.serialize_frame_globals().
def serialize_block_locals(blk = None):
    Memory._updatedNames.clear()
    block = blk if blk is not None else gdb.selected_frame().block()
    for sym in block:
        if sym.is_constant:
            continue
        desc = descriptions.MemoryDescription(sym.name, symbol = sym)
        if isinstance(desc.object, gdb.Symbol):
            continue
        obj = addressable_factory(desc)
        obj.track()
def memoryoracle.instance.serialize_frame_globals (frm = None)
Definition at line 541 of file instance.py.
References memoryoracle.instance.serialize_block_locals().
def serialize_frame_globals(frm=None):
    frame = frm if frm is not None else gdb.selected_frame()
    block = frame.block().global_block
    serialize_block_locals(block)
def memoryoracle.instance.serialize_frame_locals (frm = None)
Definition at line 566 of file instance.py.
References memoryoracle.instance.addressable_factory(), and memoryoracle.instance.get_frame_symbols().
Referenced by memoryoracle.instance.serialize_upward().
def serialize_frame_locals(frm = None):
    Memory._updatedNames.clear()
    for k in get_frame_symbols(frm = frm):
        desc = descriptions.MemoryDescription(k)
        obj = addressable_factory(desc)
        obj.track()
# def type_name(t, nameDecorators = ""):
# if t.code == gdb.TYPE_CODE_PTR:
# return type_name(t.target(), nameDecorators + "*")
# elif t.code == gdb.TYPE_CODE_ARRAY:
# length = str(t.range()[1] - t.range()[0] + 1)
# return type_name(t.target(), nameDecorators + "[" + length + "]")
# else:
# return t.name + nameDecorators
def memoryoracle.instance.serialize_upward (baseBlock = None)
Definition at line 546 of file instance.py.
References memoryoracle.instance.serialize_frame_locals().
def serialize_upward(baseBlock = None):
    if baseBlock is None:
        f = gdb.newest_frame()
    while f is not None:
        serialize_frame_locals(f)
        f = f.older()
def memoryoracle.instance.stopped (event)
Definition at line 594 of file instance.py.
def stopped(event):
    arrayData = [ v2 for k, v in Array.repository.items() for k2, v2 in v.items() ]
    with open("arrays.json", "w") as outfile:
        json.dump(arrayData, outfile, cls=StateSerializer)
    with open("pointers.json", "w") as outfile:
        json.dump(Pointer.repository, outfile, cls=StateSerializer)
    with open("structs.json", "w") as outfile:
        json.dump(Structure.repository, outfile, cls=StateSerializer)
    with open("values.json", "w") as outfile:
        json.dump(Int.repository, outfile, cls=StateSerializer)
    # with open("functions.json", "w") as outfile:
    # json.dump(Call.repository, outfile, cls=StateSerializer)
gdb.events.stop.connect(stopped)
def memoryoracle.instance.target_type_name (t)
Definition at line 582 of file instance.py.
def target_type_name(t):
    if t.code == gdb.TYPE_CODE_PTR or t.code == gdb.TYPE_CODE_ARRAY:
        return target_type_name(t.target())
    return t.name
Variable Documentation
tuple memoryoracle.instance.connection
Initial value:
= mongoengine.connect('memoryoracle',
                    read_preference=\
                            pymongo.read_preferences.ReadPreference.PRIMARY)
Definition at line 28 of file instance.py.
tuple memoryoracle.instance.d = descriptions.MemoryDescription(`a`, address=`1`, execution=e)
Definition at line 618 of file instance.py.
memoryoracle.instance.db = connection.memoryoracle
Definition at line 32 of file instance.py.
tuple memoryoracle.instance.e = execution.Execution()
Definition at line 616 of file instance.py.
tuple memoryoracle.instance.f = frame.Frame(gdb.selected_frame())
Definition at line 615 of file instance.py.
tuple memoryoracle.instance.frameDescription = descriptions.MemoryDescription(`yourframe`)
Definition at line 614 of file instance.py.
tuple memoryoracle.instance.x = Float.factory(descript=d)
Definition at line 619 of file instance.py.
Referenced by memoryoracle.test_models.ProgramTestData.set_up_class(), memoryoracle.test_models.CommitTestData.set_up_class(), memoryoracle.test_models.ExecutableTestData.set_up_class(), memoryoracle.test_models.ExecutionTestData.set_up_class(), memoryoracle.test_models.MemoryTestData.set_up_class(), memoryoracle.test_models.ObjectFileTestData.set_up_class(), memoryoracle.test_models.SourceFileTestData.set_up_class(), and memoryoracle.test_models.SymbolTestData.set_up_class().